export const navigationData = [
  { path: "/", text: "Home Page" },
  { path: "/secondscreen", text: "Second Screen" },
  { path: "/thirdscreen", text: "Third Screen" },
  { path: "/switch", text: "Switch" },
  { path: "/textinput", text: "Textinput" },
  { path: "/scrollview", text: "Scroll View" },
  { path: "/refreshcontrol", text: "Refresh Control" },
  { path: "/modal", text: "Modal" },
  { path: "/keyboardavoidingview", text: "Keyboard Avoiding View" },
  { path: "/imagebackground", text: "Image Background" },
  { path: "/filesystem", text: "Filesystem" },
  { path: "/sqlite", text: "SQLite" },
  { path: "/authentication", text: "Authentication" },
  { path: "/registeruser", text: "Register User" },
  { path: "/userlist", text: "User List" },
]
